### Register User 1
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username":"aga2221",
  "email": "anga2321@yahoo.com",
  "password": "pand12"
}

### Register User 2
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username":"aga111",
  "email": "angga111@yahoo.com",
  "password": "pand12"
}

### Login User 1
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "aga111",
  "password": "pand12"
}

### Login User 2
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "angga1",
  "password": "pand12"
}

### GET Townhall
GET http://localhost:5000/
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgxNWI5NjkyMjVkNDM1YzU0YzEzNWIiLCJpYXQiOjE2MDIzMTMxMjN9.d87BUYJmdrLBa7R8RXwEluPqeHq7ju8U5P_0bx1Tsys

#================= MARKET ========================

### GET List Market
GET http://localhost:5000/markets/5f815b969225d435c54c135b
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgxNWI5NjkyMjVkNDM1YzU0YzEzNWIiLCJpYXQiOjE2MDIzMTMxMjN9.d87BUYJmdrLBa7R8RXwEluPqeHq7ju8U5P_0bx1Tsys

### POST Market
POST http://localhost:5000/markets/
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgxNWI5NjkyMjVkNDM1YzU0YzEzNWIiLCJpYXQiOjE2MDIzMTMxMjN9.d87BUYJmdrLBa7R8RXwEluPqeHq7ju8U5P_0bx1Tsys

{
  "name": "Market001"
}

### GET by id Market
GET http://localhost:5000/markets/
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgxNWI5NjkyMjVkNDM1YzU0YzEzNWIiLCJpYXQiOjE2MDIzMTMxMjN9.d87BUYJmdrLBa7R8RXwEluPqeHq7ju8U5P_0bx1Tsys

### PUT Market
PUT http://localhost:5000/markets/:id
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjZkYTVjYTYzYjNjYjFmZDFkNDhmY2QiLCJpYXQiOjE2MDEwMjM3NjF9._nK8zthuQmx_KZbyUdG_CXB8N8k3gDbfY0zN4QPnfsw

{
  "title": "edited Todo title",
  "description": "edited"
}

### DELETE Market
DELETE http://localhost:5000/markets/:id
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjZkYTVjYTYzYjNjYjFmZDFkNDhmY2QiLCJpYXQiOjE2MDEwMjM3NjF9._nK8zthuQmx_KZbyUdG_CXB8N8k3gDbfY0zN4QPnfsw