### Register User 1
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username":"angga",
  "email": "anga@yahoo.com",
  "password": "angga"
}

### Login User 1
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "angga",
  "password": "angga"
}

### GET Townhall resources
GET http://localhost:5000/
Content-Type: application/json
access_token: 

#================= MARKET ========================

### GET List Market
GET http://localhost:5000/markets
Content-Type: application/json
access_token: 

### POST Market
POST http://localhost:5000/markets/
Content-Type: application/json
access_token: 

{
  "name": "Market001"
}

### GET by ID Market
GET http://localhost:5000/markets/:id
Content-Type: application/json
access_token: 

### PUT by ID Market
PUT http://localhost:5000/markets/:id
Content-Type: application/json
access_token: 

{
  "name": "edit Market001"
}

### DELETE Market
DELETE http://localhost:5000/markets/:id
Content-Type: application/json
access_token: 

### Collect Market
GET http://localhost:5000/markets/:id/collect
Content-Type: application/json
access_token: 