
### Login User 1
POST http://localhost:5000/attacks/5f83186c0d4ea94c525d0f7f
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

{
  "soliders":100,
}


### Register User 2
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username":"anggaupdate",
  "email": "angga4@yahoo.com",
  "password": "angga"
}


### Login User 2
POST http://localhost:5000/attacks/5f83186c0d4ea94c525d0f7f
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

{
  "soliders":0
}

### GET Townhall
GET http://localhost:5000/
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgyODViZDdlZDZhNGM2MDZjNGY3ZDYiLCJpYXQiOjE2MDI0MjUwMTd9.KJsLZWULc_muUw_3KrgGjbgYlJ5mGAqXyVS1ToYXnjU

#================= MARKET ========================

### GET List Market
GET http://localhost:5000/markets
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

### POST Market
POST http://localhost:5000/markets/
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

{
  "name": "MarketAnggasusah"
}

### GET by id Market
GET http://localhost:5000/markets/5f831b9de93ece509abbf341
Content-Type: application/json
access_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

### PUT Market
PUT http://localhost:5000/markets/5f8318a40d4ea94c525d0f80
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

{
 "name": "Market0042Update"
}

### DELETE Market
DELETE http://localhost:5000/markets/5f831b9de93ece509abbf341
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjgzMTg2YzBkNGVhOTRjNTI1ZDBmN2YiLCJpYXQiOjE2MDI0MjY5OTl9.HQdnearVDdKlrA_FkGA-QTIiGe_kcjWAHrUGA5bDQvI

